// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bddtvmypcbvvfmklwpxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJkZHR2bXlwY2J2dmZta2x3cHhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyNTAxOTcsImV4cCI6MjA2MjgyNjE5N30.G00eIMyb68gvvVHUh7Qw5Ol5ai0AmwPj3V6nsLONjeo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);